[build-system]
requires = ["setuptools >=67", "setuptools-scm >=8"]
build-backend = "setuptools.build_meta"

[project]
name = "qbittorrent-api"
requires-python = ">=3.8"
description = "Python client for qBittorrent v4.1+ Web API."
authors = [{name = "Russell Martin"}]
maintainers = [{name = "Russell Martin"}]
keywords = ["python", "qbittorrent", "api", "client", "torrent", "torrents", "webui", "web"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Utilities",
    "Topic :: Communications :: File Sharing",
]
dynamic = ["readme", "version"]
dependencies = [
    "requests >=2.16.0",
    "urllib3 >=1.24.2",
    "packaging",
]

[project.optional-dependencies]
dev = [
    "black ==23.11.0",
    "build ==1.0.3",
    "coverage[toml] ==7.3.2",
    "furo ==2023.9.10",
    "mypy ==1.7.1; platform_python_implementation != 'PyPy'",
    "pre-commit ==3.5.0",
    "pytest ==7.4.3",
    "sphinx ==7.2.6; python_version >= '3.9'",
    "sphinx-copybutton ==0.5.2",
    "sphinxcontrib-spelling ==8.0.0",
    "sphinx-autodoc-typehints ==1.25.2",
    "tox ==4.11.3",
    "twine ==4.0.2",
    "types-requests ==2.31.0.10",
    "types-six ==1.16.21.9",
]

[project.urls]
"Homepage" = "https://github.com/rmartin16/qbittorrent-api"
"Documentation" = "https://qbittorrent-api.readthedocs.io/"
"API Reference" = "https://qbittorrent-api.readthedocs.io/en/latest/api.html"
"Source" = "https://github.com/rmartin16/qbittorrent-api"

[tool.setuptools.dynamic]
readme = {file = ["README.md", "CHANGELOG.md", "LICENSE"], content-type = "text/markdown"}

[tool.setuptools_scm]
# section must be present to trigger its use

[tool.isort]
profile = "black"
skip_glob = ["venv*"]
force_single_line = true
multi_line_output = 3

[tool.black]
target-version = ["py38"]
include = '\.pyi?$'

[tool.ruff]
select = ["C40", "C9", "E", "F", "PLE", "S", "W", "YTT"]
line-length = 121
target-version = "py38"

[tool.ruff.per-file-ignores]
"tests/*" = ["C408", "S101", "S108", "S110", "S106", "S105", "C901"]

[tool.ruff.mccabe]
max-complexity = 15

[tool.pytest.ini_options]
addopts = """
  --doctest-modules
  -v
"""
filterwarnings = ["error"]
markers = [
    "skipif_before_api_version(api_version): skips test for current api version",
    "skipif_after_api_version(api_version): skips test for current api version",
]
norecursedirs = "dist build .tox scripts"
testpaths = ["tests"]

[tool.coverage.run]
parallel = true
branch = true
relative_files = true
source_pkgs = ["qbittorrentapi"]
omit = ["**/_attrdict.py"]

[tool.coverage.paths]
source = [
    "src",
    "**/site-packages",
]

[tool.coverage.report]
show_missing = true
skip_covered = true
skip_empty = true
precision = 1
exclude_lines = [
    # search categories was deprecated
    "class SearchCategoriesList",
    "def search_categories",
    # defaults to exclude
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

[tool.coverage.html]
skip_empty = true
